name: build-push-auth

on:
  # Trigger
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup google cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Build image
        run: docker build -t us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth:latest ./auth

      - name: Push image to gcr
        run: docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth:latest
