name: deploy-manifest

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ticketing repo
        uses: actions/checkout@v2

      - name: Permit github on google cloud
        uses: google-github-actions/auth@v0
        with:
          # service account credentials
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Point kubectl at specified cluster in GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Deploy manifest
        run: |
          kubectl apply -f ./infra/k8s
          kubectl apply -f ./infra/k8s-prod
