name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ticketing repo
        uses: actions/checkout@v2

      - name: Permit github on google cloud
        uses: google-github-actions/auth@v0
        with:
          # service account credentials
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure docker
        run: gcloud auth configure-docker

      - name: Build image
        run: docker build -t us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/tickets:latest ./tickets

      - name: Publish image to gcr
        run: docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/tickets:latest

      - name: Point kubectl at specified cluster in GKE
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Rollout update
        run: kubectl rollout restart deployment tickets-depl
